### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VuzzyM** [StefanIlchev/ElementumService#1]
Hello
Can I use this repository when creating own android client Libtorrent?  For torrserver https://github.com/YouROK/TorrServer

**Comment by StefanIlchev** [comment]
This project doesn't build binaries. It takes them from an Elementum Kodi addon ZIP. If they aren't available there, then they won't be in the APKs.

**Comment by VuzzyM** [comment]
@StefanIlchev 

Hello.

I propose to implement your separate project, called Libtorrent-go only for android applications, such as this project https://github.com/anacrolix/torrent

**Comment by VuzzyM** [comment]
@StefanIlchev ??
