### ISSUE TITLE
NAS write permission denied for ElementumService on NVIDIA Shield

### ISSUE THREAD

**Issue by homiee** [StefanIlchev/ElementumService#13]
Since ElementumService is installed as a system app (and not a user app), it is impossible to grant NAS write permission via the normal Settings UI.

A solution is required for non-rooted devices (e.g. installing the app as a user app instead).

Any help?

**Comment by StefanIlchev** [comment]
It's not a system app. I think some devices mistake it as such because it cannot be launched directly. Can't you just find it among the real system apps?

FYI I've made it so debug builds appear in the launcher for development purposes.

**Comment by homiee** [comment]
Great. That might work as a workaround for my device. I’ll try to build the project and install the debug build.

Thanks!

**Comment by homiee** [comment]
> Great. That might work as a workaround for my device. I’ll try to build the project and install the debug build.
> 
> Thanks!

I can confirm it works. The only issue which remains is that the debug build won’t autolaunch, and has to be opened using the launcher.

**Comment by StefanIlchev** [comment]
Please confirm that you are using debug builds for both the app and addon from the same build. Autolaunch should work.

**Comment by StefanIlchev** [comment]
My bad, autolaunch got broken when updating AGP to 7.2.0.

**Comment by JLSx168** [comment]
I opened an issue on this matter but saw this afterwards. How does the workaround work? Apologies but am not knowlegeable in installing builds. Thank you.

**Comment by homiee** [comment]
If you install the debug build version of ElementumService you can grant NAS access to the application via settings. It works great.

**Comment by homiee** [comment]
> I opened an issue on this matter but saw this afterwards. How does the workaround work? Apologies but am not knowlegeable in installing builds. Thank you.

If you install the debug build version of ElementumService you can grant NAS access to the application via settings. It works great.

**Comment by JLSx168** [comment]
> > I opened an issue on this matter but saw this afterwards. How does the workaround work? Apologies but am not knowlegeable in installing builds. Thank you.
> 
> If you install the debug build version of ElementumService you can grant NAS access to the application via settings. It works great.

Where can i find the debug build version?  Sorry am not an expert on Android system. Thanks.

**Comment by JLSx168** [comment]
> > I opened an issue on this matter but saw this afterwards. How does the workaround work? Apologies but am not knowlegeable in installing builds. Thank you.
> 
> If you install the debug build version of ElementumService you can grant NAS access to the application via settings. It works great.

Thanks!

**Comment by StefanIlchev** [comment]
I'll add the launcher in the debug version to the release version later today. Even though the app doesn't need a launcher there's no problem in having one.

**Comment by JLSx168** [comment]
> I'll add the launcher in the debug version to the release version later today. Even though the app doesn't need a launcher there's no problem in having one.

**Comment by StefanIlchev** [comment]
Done, check the [releases page](https://github.com/StefanIlchev/ElementumService/releases).

**Comment by JLSx168** [comment]
> 

Works perfectly,  much appreciated!
