### ISSUE TITLE
Path error starting elementum

### ISSUE THREAD

**Issue by Regjoz** [StefanIlchev/ElementumService#15]
After install the service APK and install the modified Zip I'm getting the error:

Stat
/storage/emulated/0/data/service.elementum.android/fi
No such file or directory 

Device:
TCL android TV 11

Kodi version:
V19.3 matrix

**Comment by StefanIlchev** [comment]
Does this error have a stacktrace in logcat?

**Comment by s0k33t** [comment]
Same problem on Nvidia shield.....

**Comment by StefanIlchev** [comment]
Where are you getting this error?
