### ISSUE TITLE
MiTV cant install

### ISSUE THREAD

**Issue by cervaens** [StefanIlchev/ElementumService#16]
Hi thanks for your work but Im no able to install the universal package in my MiTV model MTV-MOOQ0.
Android version 10.
Kernel version: 4.19.79+
Build: QTG3.200305.006.3055
I get "there was a problem parsing the app" corrupt xml binary file.
Any tips?
Thanks
Nuno

**Comment by StefanIlchev** [comment]
Sorry for not writing sooner but I had nothing to contribute and still don't. My best guess is a corrupt download.
