### ISSUE TITLE
Google Chromecast 4k with Android 12 - Kodi data on /sdcard

### ISSUE THREAD

**Issue by johnnyslt** [StefanIlchev/ElementumService#20]
Hi,

Thanks for making this possible on Android 11+ :)

Could you please check the logcat on why the Elementum doesn't work when Kodi's data path is set to /sdcard, instead of the default one /Android/data/ ?

The daemon doesn't start, I think

[logcat.txt](https://github.com/StefanIlchev/ElementumService/files/10149584/logcat.txt)

Let me know if you need more info.

Thanks !

**Comment by StefanIlchev** [comment]
It doesn't work because Elementum can't lock the file `/sdcard/kodi_data/.kodi/userdata/addon_data/plugin.video.elementum/storm.db` or any other file in shared storage because of the new storage restrictions in Android 11.

**Comment by johnnyslt** [comment]
Bummer....

Do you think it's possible to modify the path for that file to the apk data folder ? /sdcard/Android/data/service.elementum.android/files/.kodi/addons/plugin.video.elementum/

Thanks !

**Comment by StefanIlchev** [comment]
I can't think of a way to do it that would work on all devices without breaking something else. For example the path you're suggesting won't be correct on a multi user device for users other than the first one as `sdcard` is a link to his external storage. The path needs to come from Android's API to be correct but the addon has access only to Kodi's API which you're influencing with `xbmc_env.properties`.

**Comment by elgatito** [comment]
@StefanIlchev with shared library it does not work as well? There is a logic to change path to Kodi's `userdata` in special cases in Elementum. Is there a need in adjusting it?

**Comment by StefanIlchev** [comment]
@elgatito if you can find your way back to the app's external storage and work there, that would solve the issue. With the shared library it doesn't seem to get this far:

```log
bolt.Close(): funlock error: function not implemented
warning <general>: [plugin.video.elementum] Shared library execution stopped
error <general>: Exception in thread 
error <general>: Thread-2 (elementumd_thread)
error <general>: :
                 
error <general>: 
error <general>: Traceback (most recent call last):
                 
error <general>: 
error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
                 
error <general>: 
error <general>:     
error <general>: self.run()
error <general>: 
                 
error <general>: 
error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/threading.py", line 975, in run
                 
error <general>: 
error <general>:     
error <general>: self._target(*self._args, **self._kwargs)
error <general>: 
                 
error <general>: 
error <general>:   File "/storage/emulated/0/Download/Kodi/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 393, in elementumd_thread
                 
error <general>: 
error <general>:     
error <general>: for line in follow(io.open(log_path, 'r', encoding='utf8'), delay=0.5, selector=proc.is_alive):
error <general>: 
                 
error <general>: 
error <general>:   File "/storage/emulated/0/Download/Kodi/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/taller.py", line 165, in follow
                 
error <general>: 
error <general>:     
error <general>: line = self.file.readline()
error <general>: 
                 
error <general>: 
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>:  
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: ^
error <general>: 
                 
error <general>: 
error <general>: FileNotFoundError
error <general>: : 
error <general>: [Errno 2] No such file or directory
error <general>: 
                 
```

**Comment by elgatito** [comment]
@StefanIlchev That is on Android 12? What device should I emulate in Android Studio?

**Comment by elgatito** [comment]
@StefanIlchev 
I was testing shared library with this environment:

![image](https://user-images.githubusercontent.com/1247242/211078394-c51e27fb-b034-4f6f-ac3d-91a9ed2cb310.png)

**Comment by StefanIlchev** [comment]
@elgatito Android 13 TV with `/sdcard/xbmc_env.properties` containing `xbmc.data=/sdcard/Download/Kodi`.

**Comment by StefanIlchev** [comment]
@elgatito or don't lock files if it's not necessary.

**Comment by StefanIlchev** [comment]
@johnnyslt I fixed this while trying to get the addon working on Android 14, [link](https://stefanilchev.github.io/ElementumService/).

**Comment by johnnyslt** [comment]
Hi,

You actually did it ! Congrats!

It's working now 🥹

Great job !
