### ISSUE TITLE
Trackt error 503

### ISSUE THREAD

**Issue by naveen1hot** [StefanIlchev/ElementumService#21]
Hi @StefanIlchev ,
Thanks for your great work.
Just want to tell you that getting trackt error
Bad status getting top trending trackt 503
![Screenshot_20221215-073450_Kodi](https://user-images.githubusercontent.com/67212860/207755485-42a4181e-3efb-4c3c-b276-0dc0c3722c1d.png)

Pls resolve the issue if possible.
Platform Android vi
Kodi 19.4

**Comment by StefanIlchev** [comment]
It seems like their systems are [down](https://status.trakt.tv/).
