### ISSUE TITLE
Elementum service stopped working 

### ISSUE THREAD

**Issue by ninormalen** [StefanIlchev/ElementumService#22]
Hi,
Since today elementum service has stopped working. After I start today to watch something message "elementum service has started" appears and movie has stopped. I try to reinstall apk file and kodi but nothing happened. Here log. I am sorry but on Chromecast with Google tv I can't copy log file.
https://drive.google.com/drive/folders/1bx8kVrdBqK1fo3qD-FZCgFmdBgqTVjIq
Please take a look.

**Comment by StefanIlchev** [comment]
@ninormalen, that's fine, I don't need Kodi's log file anyway. Instead use the following command in `adb shell` to start recording Android's log:

```bat
logcatLog=/sdcard/Download/logcat.log; logcat -c; logcat >$logcatLog & pid=$!; read; echo '\n--------- beginning of kill logcat' >>$logcatLog; kill $pid >>$logcatLog 2>&1; echo '\n---------    ending of kill logcat' >>$logcatLog
```

To stop it enter:

```bat
some non-empty text
```

Now can you please do the following in this order:

1. start logging;
2. start Kodi;
3. cause the plugin/daemon to crash and restart at least once;
4. stop Kodi;
5. start Kodi;
6. wait for the notification;
7. stop Kodi;
8. stop logging;
9. upload the log.

**Comment by ninormalen** [comment]
Hi, today works fine. 🤔
Sorry to bother you. Thank you.
