### ISSUE TITLE
Kodi Nexus

### ISSUE THREAD

**Issue by ninormalen** [StefanIlchev/ElementumService#24]
Hi, after update Kodi to version 20, when I watch something and I try to watch something else, elementum not load seeders and Kodi crash and closes. My device is Chromecast with Google tv, android 12. This only happens when I start second video. When I open Kodi again elementum work's fine to first video, but on second crashes again. This is happening every time.

**Comment by StefanIlchev** [comment]
Seems to be an issue with the main project as it's reported there as well:

https://github.com/elgatito/plugin.video.elementum/issues/669#issuecomment-1435662208
