### ISSUE TITLE
Kodi 20 Elementum plugin not starting

### ISSUE THREAD

**Issue by nfilipek** [StefanIlchev/ElementumService#25]
Last update of Elementum plugin and service in new Kodi 20 result in error. Elementum plugin cannot start in new kodi. Version before that new was working fine with new kodi 20

**Comment by StefanIlchev** [comment]
It's working fine for me. If you're using version 0.1.870002 which could not start on some devices, update again to version 0.1.870003. If that doesn't work, I'm going to need some logs. If you don't know how to get them, check some of the other issues, like for example https://github.com/StefanIlchev/ElementumService/issues/12.

**Comment by nfilipek** [comment]
I just installed a new version 870004 but it still cannot comunicate with service plugin. I also updated a service plugin but no luck. I then installed kodi 19.5 Matrix and in kodi 19.5 it is working. 
The only plugin and service that is working in kodi 20 for me is the 870001 version. 
I am using nvidia shield tv pro. I think it is on Android 11

**Comment by StefanIlchev** [comment]
Did you try manually installing both the app and the addon?

**Comment by nfilipek** [comment]
For some reason I cannot see any files in that directory from kodi 20 but I cann see it from kodi 19. I dont know what is happening with this kodi 20. I have all elementum plugins in this folder but I cannot see any of them when I go to Kodi 20 and install from zip file.

**Comment by nfilipek** [comment]
I think I just leave it to version 870001 and use it in kodi 20.

**Comment by StefanIlchev** [comment]
The only reason I can think of for not seeing any files is that Kodi doesn't have the new all files access permission which was introduced in Android 11 and is mandatory for newer apps such as Kodi 20. You won't find it in the app's settings though, you need to go to "special app access" or something like that.

**Comment by nfilipek** [comment]
I have found a solution! 
1. Last plugin 870004 is working with kodi 20
2. Go to settings, apps and find Kodi
3. Click on Kodi and go down to Permissions
4. Turn off remove permissions if app isnt used
5.  Click on Files and Media
6. It is se to allow all the time but change it to Alow only while using the app and click to go back
7. Then click again to Files and Media and then click on Allow all the time an then click allow once more.
8. After that all files in all folders are visible in kodi 20 and elementum plugin version 870004 is working normaly.

Thank you Stefan for updating and maintaining this plugin and service!

**Comment by StefanIlchev** [comment]
You're welcome!

I am glad to hear that you got it working.

**Comment by gitixus** [comment]
> I have found a solution!
> 
>     1. Last plugin 870004 is working with kodi 20
> 
>     2. Go to settings, apps and find Kodi
> 
>     3. Click on Kodi and go down to Permissions
> 
>     4. Turn off remove permissions if app isnt used
> 
>     5. Click on Files and Media
> 
>     6. It is se to allow all the time but change it to Alow only while using the app and click to go back
> 
>     7. Then click again to Files and Media and then click on Allow all the time an then click allow once more.
> 
>     8. After that all files in all folders are visible in kodi 20 and elementum plugin version 870004 is working normaly.
> 
> 
> Thank you Stefan for updating and maintaining this plugin and service!

I had the same problem and I was able to solve it this way. Thanks!!! And thanks, Stefan!

**Comment by nfilipek** [comment]
When a new update for Kodi is released maybe we should repeat that procces once again if elementum plugin is not comunicating with elementum service. I dont know.

**Comment by StefanIlchev** [comment]
@nfilipek, there was a bug that was causing only the addon to update and not the app. I fixed it in the new version but the app will need to be updated manually one more time. I apologize for the inconvenience.
