### ISSUE TITLE
Elementum service 0.1.910001 error with: Elementum is still starting up, give it a few seconds

### ISSUE THREAD

**Issue by ezaharinov** [StefanIlchev/ElementumService#26]
Elementum service and client have been updated to the latest 0.1.910001 version and I have updated manually the apk. The client I have updated it from the Kodi repository.

Current device:
Chromecast TV
Kodi version: Nexus 20.2

Check:

1. Force stop the Service application
2. run the Kodi
3. Run Elementum client -> No version difference error != version as ElementumService -> same error but the Service application is started in the applications menu
4. Check if there is a running application -> application is running

Is there anyone experiencing this problem?

Should I try with lower versions?

**Comment by StefanIlchev** [comment]
It's working fine for me. Could you share the log from after this happens by executing the following command:

```bat
adb logcat -d
```

**Comment by ezaharinov** [comment]
I figured it out
You need to set permissions for Kodi to access all files. My settings were to prompt for access.

With your previous versions, there were no issues with prompt access.

### In the future if people are having issues with permissions:

1. Make sure Kodi has permission to access all files
2. Make sure the Elementum application (apk) that you installed has full permissions as well.

> It's working fine for me. Could you share the log from after this happens by executing the following command:
> 
> ```batchfile
> adb logcat -d
> ```

Regarding this command -> I don't know where to execute it - maybe there is a good reason for a readme for debugging ^^

Thanks for your great work!
Best regards,

**Comment by StefanIlchev** [comment]
@ezaharinov I have no problems using the addon without granting the service app permission to access the storage, but I cannot start Kodi without storage permission. It shows an error `Permission denied!! Exiting...`. Kodi's version is 21.0-ALPHA2 on Android 14 Beta.
