### ISSUE TITLE
[solved] Movies Library

### ISSUE THREAD

**Issue by davordragic** [StefanIlchev/ElementumService#28]
I'm having issues showing My collection from Trakt in Kodi main screen section Movie.
On other hand, section TV Shows work fine.

My settings:
Elementum - Library path (/storage/emulated/0/elementum/ - since I did not know how to find "special" folder in Library)

If I look at this folder via File explorer, I can see that /storage/emulated/0/elementum/tv shows has content (tv shows in my collection on trakt.tv), while /storage/emulated/0/elementum/movies is empty. Despite having 10+ movies in my Collection on Trakt.tv.

Can anyone help how to find the issue?

**Comment by StefanIlchev** [comment]
It sounds like you're doing everything correctly as far as this project is concerned. The path you've chosen will be visible to both Kodi and the service app as long as they have storage permissions so no problem there.

**Comment by davordragic** [comment]
I just noticed that movie I added after all setting, has appeared in Kodi Linrary. Old movies did not

**Comment by StefanIlchev** [comment]
Sounds like an issue with [Elementum](https://github.com/elgatito/plugin.video.elementum) itself. You should try asking there.

**Comment by davordragic** [comment]
Oh I'm sorry. I wrote on wrong repo.
But just to replay, because I manage to sort this.

I clean all the data from Kodi, reinstalled Elementum. Only important step was, that I have set the new folder path for Libarary in Elementum before I have made a login to Trakt.tv. With this flow, all works fine.

**Comment by davordragic** [comment]
Closing issue, because bug does not belong to this repotory.
