### ISSUE TITLE
release 0.1.86.4.apk

### ISSUE THREAD

**Issue by earlgray44** [StefanIlchev/ElementumService#4]
Installing this causes elementum to not start, or hang with "looks like elementum is still starting up" message. Reverting to 1.86.3 fixes things.
Running e 1.86, Nvidia shield, android 11

**Comment by StefanIlchev** [comment]
Can you give me logs as it works fine for me. Use the following commands:

```bat
adb logcat -d -s MainActivity
```

```bat
adb logcat -d -s ForegroundService
```

```bat
adb logcat -d -s plugin.video.elementum
```

**Comment by earlgray44** [comment]
Haven't done that before but I'll certainly give it a try. Won't have time until later today though. My thanks for your time and attention. 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 12:03 PM, ***@***.***> wrote:   


Can you give me logs as it works fine for me. Use the following commands:
adb logcat -d -s MainActivityadb logcat -d -s ForegroundServiceadb logcat -d -s plugin.video.elementum
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StefanIlchev** [comment]
I just released a new version containing some minor code cleanup. It's not going to fix your problem but please install it and launch Kodi. Then wait for however long it usually takes Elementum to start on your device and if nothing happens run the commands I gave you in my previous comment and paste the results here.

**Comment by earlgray44** [comment]
Sorry if this is a pain, but I couldn't get the logcat results to save to a file so I'm sending an image. This is after elementum fails to start using your 1.86.5 apk. Hope this helps. Again, your work is much appreciated!

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 1:29 PM, ***@***.***> wrote:   


I just released a new version containing some minor code cleanup. It's not going to fix your problem but please install it and launch Kodi. Then wait for however long it usually takes Elementum to start on your device and if nothing happens run the commands I gave you in my previous comment and paste the results here.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by earlgray44** [comment]
Just so we're clear, everything works fine for my system on the 1.86.3 apk. It's only the . 4 and now the . 5 versions that give trouble. 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 4:08 PM, gary ***@***.***> wrote:   
Sorry if this is a pain, but I couldn't get the logcat results to save to a file so I'm sending an image. This is after elementum fails to start using your 1.86.5 apk. Hope this helps. Again, your work is much appreciated!

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 1:29 PM, ***@***.***> wrote:   


I just released a new version containing some minor code cleanup. It's not going to fix your problem but please install it and launch Kodi. Then wait for however long it usually takes Elementum to start on your device and if nothing happens run the commands I gave you in my previous comment and paste the results here.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChristianCiach** [comment]
I was able to reproduce the issue in the latest two releases (0.1.86.4 and 0.1.86.5).

The logcat was empty exact for these lines:

```
--------- beginning of system                           --------- beginning of main                             01-15 23:27:32.025 31913 31913 V MainActivity: deniedPermissions = [android.permission.MANAGE_EXTERNAL_STORAGE] 01-15 23:27:44.286 31913 31913 V MainActivity: deniedPermissions = [android.permission.MANAGE_EXTERNAL_STORAGE] 01-15 23:32:42.241 32598 32598 V MainActivity: deniedPermissions = [android.permission.MANAGE_EXTERNAL_STORAGE] 
```

I did the `appops` command to allow MANAGE_EXTERNAL_STORAGE for the package, but this didn't help immediately.

I got it working again by going to "Settings -> Apps -> See all apps -> Elementum Service" and selecting "Open". I don't know why this helped. Maybe we have to manually restart the Activity after giving it the necessary permissions? But I don't understand why the previous release worked perfectly fine and the new releases are more complicated to get it working. 

By the way: The dialog that shows the necessary adb commands only pops up for a split second and disappears immediately. 

Another thought: Do you really need to target the Android 11 SDK version? Wouldn't it be easier to target the same SDK version as Kodi itself and use the legacy permissions instead of MANAGE_EXTERNAL_STORAGE?

**Comment by ChristianCiach** [comment]
> By the way: The dialog that shows the necessary adb commands only pops up for a split second and disappears immediately.

This may have been my fault. Maybe I just pressed the button on the remote too fast and immediately closed the dialog by accident.

**Comment by earlgray44** [comment]
Reading this, I uninstalled the. 3 apk, installed the. 5 which had previously failed. This time, I selected "open" when installation was done. Hadn't done so previously since opening the apk didn't appear to do anything before. This time, I got a dialog box requesting permission. After that, elementum runs fine. 
Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 4:57 PM, ***@***.***> wrote:   



By the way: The dialog that shows the necessary adb commands only pops up for a split second and disappears immediately.


This may have been my fault. Maybe I just pressed the button on the remote too fast and immediately closed the dialog by accident.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by earlgray44** [comment]
I spoke too soon. While elementum starts, which it hadn't before, it then hangs with the "starting up" message.... 😑

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 5:10 PM, gary ***@***.***> wrote:   Reading this, I uninstalled the. 3 apk, installed the. 5 which had previously failed. This time, I selected "open" when installation was done. Hadn't done so previously since opening the apk didn't appear to do anything before. This time, I got a dialog box requesting permission. After that, elementum runs fine. 
Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 4:57 PM, ***@***.***> wrote:   



By the way: The dialog that shows the necessary adb commands only pops up for a split second and disappears immediately.


This may have been my fault. Maybe I just pressed the button on the remote too fast and immediately closed the dialog by accident.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StefanIlchev** [comment]
I think I get what's happening. In versions before 0.1.86.4 a device not having the UI for MANAGE_EXTERNAL_STORAGE wasn't handled because I didn't believe such devices would actually exist apart from some custom images. And the app's behavior when an unhandled situation occurs is to start the service anyway as it might work which it apparently kind of does. But now it's handled with a dialog whose dismissal is interpreted as not wanting to grant the permission in which case the app closes itself as it can't provide Elementum with all that it needs.

I released another new version in which I removed OK button from the allow manage external storage command dialog because it was misleading people into thinking it executed the command instead of just showing it. I also made the dialog harder to dismiss manually but it'll dismiss automatically when you execute the command.

@ChristianCiach no, I don't currently need to target the latest version as compatibility mode for this still works but eventually, I might have to so might as well deal with it now. Kodi will have to deal with this sooner or later as well if it wants to stay in the Play store which has a minimum target version that is constantly increased regardless of whether new Android versions can still run older sideloaded apps.

**Comment by ChristianCiach** [comment]
I wonder how Kodi will handle this, because MANAGE_EXTERNAL_STORAGE is a permission that Google only allows for some extremely specific use case, like file managers or virus scanners, otherwise the apps won't be allowed into the Play store.

**Comment by StefanIlchev** [comment]
@earlgray44 if you were happy with the way 0.1.86.3 worked and don't want to bother with commands then try the latest and hopefully last release related to this - 0.1.86.7. It has a deny button that will dismiss the dialog and it will never appear again unless you clear the app's data or uninstall and install it again. Now there are no loose threads ☺️

@ChristianCiach Kodi might be able to pass for a file manager. It has a file manager button in settings. Microsoft's office apps have the permission and file managing isn't their primary purpose. Another option is to use [scoped storage](https://developer.android.com/training/data-storage#scoped-storage) if it works for them. And before you ask no, Elementum's executable doesn't work with [scoped storage](https://developer.android.com/training/data-storage#scoped-storage) or at least I can't think of a way it would.

**Comment by earlgray44** [comment]
Thanks, no loose threads! ☺️👍It was easy to be happy with the 0.1.86.3 apk because it restored all the functionality of elementum l had on the Nvidia before the replatforming to Android 11.I have always been able to get elementum to write to an external drive for the past two years so I don't think I was tracking the functionality you were reaching for with the adb command. Not necessary for my use case, I guess. I'd love for elementum to be able to write to NAS, and I forgot what I learned back then about what constrains it from doing that - some android limitation was it? And the MANAGE_EXTERNAL_STORAGE command doesn't do anything to affect that. Tried 0.1.86.7 and had no problems. Congratulations again on a great and most helpful effort. 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 9:20 PM, ***@***.***> wrote:   


@earlgray44 if you were happy with the way 0.1.86.3 worked and don't want to bother with commands then try the latest and hopefully last release related to this - 0.1.86.7. It has a deny button that will dismiss the dialog and it will never appear again unless you clear the app's data or uninstall and install it again. Now there are no loose threads ☺️
 
@ChristianCiach Kodi might be able to pass for a file manager. It has a file manager button in settings. Microsoft's office apps have the permission and file managing isn't their primary purpose. Another option is to use scoped storage if it works for them. And before you ask no, Elementum's executable doesn't work with scoped storage or at least I can't think of a way it would.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by earlgray44** [comment]
Gosh man, just checked in and found we were up to ver 11! And I thought ver 7 was the very last! 😜
Now that I've had my laugh, I installed ver 11, complete with adb command, and all is well. Just thought you'd like to know... 
Sent from Yahoo Mail on Android 
 
  On Sun, Jan 16, 2022 at 12:22 PM, gary ***@***.***> wrote:   Thanks, no loose threads! ☺️👍It was easy to be happy with the 0.1.86.3 apk because it restored all the functionality of elementum l had on the Nvidia before the replatforming to Android 11.I have always been able to get elementum to write to an external drive for the past two years so I don't think I was tracking the functionality you were reaching for with the adb command. Not necessary for my use case, I guess. I'd love for elementum to be able to write to NAS, and I forgot what I learned back then about what constrains it from doing that - some android limitation was it? And the MANAGE_EXTERNAL_STORAGE command doesn't do anything to affect that. Tried 0.1.86.7 and had no problems. Congratulations again on a great and most helpful effort. 

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 15, 2022 at 9:20 PM, ***@***.***> wrote:   


@earlgray44 if you were happy with the way 0.1.86.3 worked and don't want to bother with commands then try the latest and hopefully last release related to this - 0.1.86.7. It has a deny button that will dismiss the dialog and it will never appear again unless you clear the app's data or uninstall and install it again. Now there are no loose threads ☺️
 
@ChristianCiach Kodi might be able to pass for a file manager. It has a file manager button in settings. Microsoft's office apps have the permission and file managing isn't their primary purpose. Another option is to use scoped storage if it works for them. And before you ask no, Elementum's executable doesn't work with scoped storage or at least I can't think of a way it would.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by StefanIlchev** [comment]
I'm glad to hear it and yeah I kept thinking of small improvements or finding bugs to fix around the only UI this app has - the Android 11 for TV manage external storage allow command dialog. When I initially made this I didn't imagine I'd ever need to add any UI so I took advantage of that which came back to bite me 😅

If I don't think of anything else the next version should be when there is a major update from Android or if the main project releases a new version.
