### ISSUE TITLE
Library Integration Issue

### ISSUE THREAD

**Issue by henshin** [StefanIlchev/ElementumService#8]
I'm running Kodi on a Shield Pro (Android 11).
I've noticed that after installing the Elementum service, my library stopped being updated when I added new movies to the library via Elementum. Took me a while to pinpoint the issue but I believe it's because of this that you mentioned on the README:
> You'll no longer be able to use paths to [Kodi](https://github.com/xbmc/xbmc)'s data folder as they will be translated to the service app's data folder.

I can see the movies are added to `/storage/emulated/0/Android/data/service.elementum.android/files/.kodi/temp/elementum_library/Movies` but this is not the directory that Kodi is using in the library, so I think this is the reason why I don't see updates on my library. My library is currently configured to use the `special://temp/elementum_library/Movies` directory which translates to `/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum_library/Movies`. 
I tried to change this to use the `service.elementum.android` directory mentioned above but it obviously fails since those files belong to a diferent app (the Elementum Service) and Kodi can't access them.
Is there a workaround for this?

Thanks in advance!

**Comment by ChristianCiach** [comment]
I didn't try it myself, but the only solution I can think of is to move Kodi's data directory to the external storage. Specifically you have to move it to a folder that is excpliticly world-writable, like `/NVIDIA_SHIELD` or `/Download`. 

See this post for how to move the directory: https://www.reddit.com/r/ShieldAndroidTV/comments/nnv043/update_guide_how_to_move_kodi_user_data_and/

**Comment by StefanIlchev** [comment]
You can try using a folder that is accessible by both Kodi and ElementumService so path translation isn't used for this. For example:
`/storage/emulated/0/Elementum/Library`

**Comment by henshin** [comment]
Thanks for the quick reply!
@ChristianCiach: I think the issue is that Kodi cannot access the `service.elementum.android` files. So it's not a permission problem in the Kodi side, it's on the ElementumService side.
@StefanIlchev That could work but how can I configure ElementumService to use a different path?

**Comment by StefanIlchev** [comment]
Elementum -> Settings -> General -> Library path

**Comment by henshin** [comment]
That worked! Thanks both @StefanIlchev and @ChristianCiach for your help.
For anyone else searching for a solution for the same problem, this is what I've done:
1. Using `adb shell`, access your device and create the directory `/storage/emulated/0/Elementum/Library` as suggested by Stefan. The directory will have the `root:everybody` ownership
2. Create directories `Movies` and `Shows` inside `/storage/emulated/0/Elementum/Library`
3. In Kodi main menu, go to `Videos` > `Files` and make sure your Movies and TV Shows nodes point to the previously mentioned directories respectfully
4. In Elementum settings go to `General` > `Library Path` and set it to `/storage/emulated/0/Elementum/Library`
5. Update the Library

If you are using Trakt, you can now go to Elementum settings > `Trakt` > `Update Trakt` and the synchronization will start. Any future content you add to the library will be synchronized correctly between Kodi - ElementumService - Trakt.

**Comment by StefanIlchev** [comment]
@henshin, you're welcome.

BTW, you can remove 2 and put 4 in its place as `Movies` and `Shows` will be created for you when you set `Library Path`.

Also, you can create the directories as you're setting `Library Path`. Kodi's picker has a "New folder" button.
