### ISSUE TITLE
Request for lt2http.

### ISSUE THREAD

**Issue by 7Wuf8xG46TjwTtqYsNMJ** [StefanIlchev/ElementumService#9]
Hey, this is more of a request than an issue but I'm unsure of how else to ask, I've been using your elementum service fix for a while now and I appreciate your work in fixing elementum, it's been working perfectly without any issues, I just wondered if you'd ever consider making a version of the fix for lt2http from the same developer?

Many thanks.

https://github.com/ElementumOrg/service.lt2http

**Comment by StefanIlchev** [comment]
You're welcome ☺️

https://github.com/StefanIlchev/Lt2httpService

Luckily the code was very similar so it wasn't too much work.

I don't use this addon but from what I can tell it seems to work now.

**Comment by 7Wuf8xG46TjwTtqYsNMJ** [comment]
Thank you so much for making this, I just tested it and it works perfectly, amazing work as always, I really do appreciate it as for what it is well it's a service for kodi that uses the same process as elementum basically it allows you to control torrents remotely using commands allowing you to make scripts around it, if you want to know what exactly it can do just open kodi and when the service starts type your devices ip address followed by the port 65225 and you will get a link to the documentation page, I'll give an example below and will close this issue now, again thank you for making this.

Example:
192.168.1.150:65255
This will give you a link to:
192.168.1.150:65255/swagger/ui
Here you will find all the functionality of the service.
